### PR TITLE
Bug Fix #21

### LINKED ISSUE #21: bug: Api Config
Hello!

I've come across a bug wherein clicking on the API: Free button, selecting the "Use your own API key" option from the modal, and then clicking on the cancel button still results in the configuration being updated to "Use your own API key" from "Free".

To reproduce the bug: clicking on "cancel" button in the "Use your own API key" modal doesn't revert configuration to "Free"

### PR DESCRIPTION
**Pull request by llegomark**
The issue with the code lies in the handleSave function of the ApiMenu component, specifically in the if (apiFree === true) condition. When apiFree is true, the handleSave function closes the modal, regardless of whether the user selected "Use your own API key" or "Use free API provided by Ayaka" before clicking the "Cancel" button. This means that the configuration is not being reverted back to "Free" even though the user canceled the selection of their own API key.

To fix the bug, we will need to update the handleSave function to properly handle the "Cancel" button. One approach is to introduce a new state variable called selectedApiFree that tracks the user's selected API option. We can set it to the initial value of apiFree, and update it whenever the user toggles the radio buttons. Then, in the handleSave function, we can use selectedApiFree instead of apiFree to determine whether to close the modal or update the API key. With this approach, clicking "Cancel" will revert the configuration to the previously selected option.

Note that in the updated code, setSelectedApiFree(true) corresponds to selecting "Use free API provided by Ayaka", while setSelectedApiFree(false) corresponds to selecting "Use your own API key".

Reference: #21

### CODE REVIEW

File: src/components/ApiMenu/ApiMenu.tsx [hunk 1]
```diff
@@ -16,17 +16,20 @@ const ApiMenu = ({
   const apiFree = useStore((state) => state.apiFree);
   const setApiFree = useStore((state) => state.setApiFree);
 
+  const [selectedApiFree, setSelectedApiFree] = useState<boolean>(apiFree);
```
Comment (ztjhz) [inline src/components/ApiMenu/ApiMenu.tsx:19]: let's change `selectedApiFree` to `_apiFree` and `setSelectedApiFree` to `_setApiFree`, so that it is consistent with the `_apiKey` and `_setApiKey`.

File: src/components/ApiMenu/ApiMenu.tsx [hunk 2]
```diff
@@ -40,7 +43,7 @@ const ApiMenu = ({
 
   useEffect(() => {
     if (apiKey) {
-      setApiFree(false);
+      setSelectedApiFree(false);
```
Comment (ztjhz) [inline src/components/ApiMenu/ApiMenu.tsx:46]: The original intention of the following code is to automatically switch the user to use their own api key if they already have one stored inside their `localstorage`. In addition, the code would automatically toggle the radio button to the custom api option when they open up the menu.
```javascript
useEffect(() => {
    if (apiKey) {
      setApiFree(false);
      _setApiKey(apiKey);
    }
  }, []);
```

I would suggest that we keep `setApiFree(false)` and add another line for the local state: `_setApiFree(false)`.

**Review by ztjhz — CHANGES_REQUESTED** [review]
Looks good! Just some minor changes to be made.

**Review by saliksik — APPROVED** [review]

File: src/components/ApiMenu/ApiMenu.tsx [hunk 3]
```diff
@@ -43,7 +42,7 @@ const ApiMenu = ({
 
   useEffect(() => {
     if (apiKey) {
-      setSelectedApiFree(false);
+      _setApiFree(false);
```
Comment (ztjhz) [inline src/components/ApiMenu/ApiMenu.tsx:45]: Please add `setApiFree(true)`

**Review by ztjhz — CHANGES_REQUESTED** [review]

File: src/components/ApiMenu/ApiMenu.tsx (hunk 3 above)
Comment (llegomark) [reply src/components/ApiMenu/ApiMenu.tsx:45]: May I know if this is want you meant?   useEffect(() => {
    setApiFree(true);
    if (apiKey) {
      _setApiFree(false);
      _setApiKey(apiKey);
    }
  }, []);

Comment (ztjhz) [reply src/components/ApiMenu/ApiMenu.tsx:45]: Sorry, I meant the following:
```javascript
useEffect(() => {
  if (apiKey) {
  setApiFree(false);
  _setApiFree(false);
  _setApiKey(apiKey);
}
}, []);
```

**Review by ztjhz — APPROVED** [review]
